# About UAC in GitHub Action (https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#:~:text=Windows%20virtual%20machines%20are%20configured%20to%20run%20as%20administrators%20with%20User%20Account%20Control%20(UAC)%20disabled.%20For%20more%20information)

name: MSBuild

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - uses: MinoruSekine/setup-scoop@v1

      - name: build/light ver.
        run: |
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/SARDONYX-sard/dotfiles/main/install-win.ps1')
        env:
          DOTFILES_INSTALL_MODE: lightweight
